AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla DevOps - EC2 con LabInstanceProfile y Bucket S3 con Versionado

Resources:
  # 1. Instancia EC2 t2.micro
  ServidorWeb:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0440d3b780d96b29d # Amazon Linux 2023 en us-east-1
      # Asignación del perfil de instancia permitido por el Lab
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: Servidor-Proyecto-Omar

  # 2. Bucket S3 con nombre dinámico y versionado
  BucketDatos:
    Type: AWS::S3::Bucket
    Properties:
      # Generación dinámica del nombre usando el ID de la cuenta
      BucketName: !Sub "bucket-proyecto-finanzas-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  IDInstancia:
    Description: ID de la instancia EC2 creada
    Value: !Ref ServidorWeb
  NombreBucket:
    Description: Nombre del bucket S3 generado dinámicamente
    Value: !Ref BucketDatos
