version: '3.8'

services:
  web:
    image: docker-web
    ports:
      - "5000:5000"
    networks:
      - devops_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - devops_network

networks:
  devops_network:
    external: true
