version: '3.8'
services:
  web:
    image: docker-web
    container_name: flask_app
    networks:
      - devops_network
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    networks:
      - devops_network
networks:
  devops_network:
    external: true
