name: Validacion Ultra Final

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: pip install boto3 flask
    - name: Validar Sintaxis Real
      run: |
        python -m py_compile automatizacion.py
        bash -n setup.sh usuarios.sh limpieza_logs.sh
