name: Pipeline_Final_Omar_V2

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: pip install boto3 flask

    - name: Validar sintaxis
      run: |
        python -m py_compile automatizacion.py
        bash -n setup.sh usuarios.sh limpieza_logs.sh
