name: Pipeline CI/CD Proyecto Final

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        pip install boto3 flask

    - name: Validar sintaxis de scripts Python
      run: |
        python -m py_compile automatizacion.py app/app.py

    - name: Validar sintaxis de scripts Shell
      run: |
        bash -n setup.sh usuarios.sh limpieza_logs.sh
